O
object.name
property.name
function.name
function.args_start
function.args_end
variable.name
declaration.variable
operator.assignment
string.string_start
string.string_end
literal.array.start
literal.array.end
literal.object.start
literal.object.end
separator
statement_end