O
global_object.name
property.name
function.name
function.args_start
function.args_end
variable.name
declaration.variable
operator.assignment
literal.string.start
literal.string.end
literal.array.start
literal.array.end
literal.object.start
literal.object.end
literal.object.end
literal.object.delimiter
statement_end