object.name
property.name
function.name
function.args_start
function.args_end
variable.name
declaration.variable
operator.assignment
string.string_start
string.string_end
list.start
list.end
separator
statement_end
O